export const EXPENSE_CATEGORIES = [
  'Makanan & Minuman',
  'Transportasi',
  'Belanja',
  'Hiburan',
  'Kesehatan',
  'Pendidikan',
  'Rumah Tangga',
  'Pakaian',
  'Kecantikan',
  'Olahraga',
  'Hadiah',
  'Amal',
  'Tagihan',
  'Utilitas',
  'Komunikasi',
  'Parkir',
  'Bensin',
  'Tol',
  'Perawatan Kendaraan',
  'Elektronik',
  'Furnitur',
  'Perbaikan Rumah',
  'Hewan Peliharaan',
  'Hobi',
  'Langganan',
  'Software & Apps',
  'Gaming',
  'Travelling',
  'Hotel & Penginapan',
  'Tiket Pesawat',
  'Pajak',
  'Denda',
  'Transfer',
  'Lainnya',
];

export const INCOME_CATEGORIES = [
  'Gaji',
  'Bonus',
  'Investasi',
  'Bisnis',
  'Freelance',
  'Hadiah',
  'Komisi',
  'Tunjangan',
  'Cashback',
  'Penjualan',
  'Dividen',
  'Bunga',
  'Sewa',
  'Royalti',
  'Refund',
  'Transfer',
  'Saldo Awal',
  'Lainnya',
];

export const BILL_CATEGORIES = [
  'Listrik',
  'Air',
  'Gas',
  'Internet',
  'Telepon',
  'TV Kabel',
  'Streaming',
  'Asuransi Kesehatan',
  'Asuransi Kendaraan',
  'Asuransi Jiwa',
  'Cicilan Motor',
  'Cicilan Mobil',
  'Cicilan Rumah',
  'Cicilan KPR',
  'Kartu Kredit',
  'Pinjaman Bank',
  'Sewa Rumah',
  'Sewa Kos',
  'IPL',
  'Pajak PBB',
  'Pajak Kendaraan',
  'Spotify',
  'Netflix',
  'Disney+',
  'YouTube Premium',
  'iCloud',
  'Lainnya',
];

export const EWALLET_OPTIONS = [
  'GoPay',
  'OVO',
  'Dana',
  'ShopeePay',
  'LinkAja',
  'Jenius',
  'PayPal',
  'Lainnya',
];

export const BANK_OPTIONS = [
  'BCA',
  'Mandiri',
  'BNI',
  'BRI',
  'CIMB Niaga',
  'Permata',
  'Danamon',
  'BTN',
  'Mega',
  'Panin',
  'OCBC NISP',
  'Bank Jago',
  'Jenius (BTPN)',
  'Blu (BCA Digital)',
  'Seabank',
  'Neo Commerce',
  'Lainnya',
];

export type WalletType = 'cash' | 'e-wallet' | 'bank';
export type TransactionType = 'income' | 'expense' | 'bill';
export type RecurringType = 'tidak' | 'harian' | 'mingguan' | 'bulanan' | 'custom';
